server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 2000
          cloud-payment-service:
            connect-timeout: 3000
            read-timeout: 3000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048
        response:
          enabled: true
logging:
  level:
    com:
      atguigu:
        cloud:
          apis:
            PayFeignApi: debug